name: latex-main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  latex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          latexmk_shell_escape: true
          root_file: tasksheet.tex
      
      - uses: actions/upload-artifact@v3
        with:
          name: task-sheets
          path: |
            */*.pdf
  
  release:
    runs-on: ubuntu-latest
    needs: latex

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: task-sheets
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            **/*.pdf
            
